name: ${name}
description: Easy solution for saving and retrieving books.
version: ${version}
author: LankyLord
main: net.lankylord.booksave.BookSave

commands:
  book:
    description: The commands for interfacing with BookSave
    aliases: [bs, booksave]