name: BookSave
description: Easy solution for saving and retrieving books.
version: maven-version-number
author: LankyLord
main: net.lankylord.booksave.BookSave

commands:
  book:
    description: The commands for interfacing with BookSave
    aliases: [bs, booksave]